### ISSUE TITLE
Order status not set on processing for every paid order

### ISSUE THREAD

**Issue by jdereus87** [MultiSafepay/magento2#10]
A customer is experiencing an issue where for some orders the order status does not get switched to processing after an order is paid, but stays on pending. Setting the order states in the MSP config does not make a difference.

Magento 2.3.6 with:
-        "multisafepay/magento2-core": "^2.0",
-        "multisafepay/magento2-frontend": "^1.1",
-        "multisafepay/magento2-catalog-inventory": "^1.0",
-        "multisafepay/magento2-adminhtml": "^1.1"

Comparing two orders where the status has been changed / not changed, the multisafepay log does not show any difference. Is this a known issue that has been fixed in later versions? Because I have updated the modules, but I am encountering a different (and with more impact) issue there, which I will post in a separate issue.

**Comment by vinodsowdagar** [comment]
Hi @jdereus87 ,

This issue has been fixed from version 2.3.1.
See the changelog for more details: https://github.com/MultiSafepay/magento2/releases/tag/2.3.1

I have replied on the other issue as well. Let's continue the conversation there.
For now i will close this one.
