### ISSUE TITLE
Payment status stays Pending Payment

### ISSUE THREAD

**Issue by onepack** [MultiSafepay/magento2#16]
**Describe the bug**
In Test mode I just did two Ideal transactions with the testing status "complete".
I get redirected to the Success page and all seems fine.
In the order overview it actually seems that there has not been a valid payment.
The amount is still open and the status is "Pending Payment".

**To Reproduce**
1. Enable testing via testing api key
2. Enable Ideal only
3. Place an order in the frontend with status complete in the MSP testing env.
4. Get redirected to the Success page
5. Check the orders in the backend now and see that the order has the status pending payment and the complete amount is due payment.
6. Tried to fix it by running the cron via cli and the reindex
7. No luck

**Expected behavior**
After a successful iDeal payment the order should have status "processing".

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Magento: 2.4.2-p1

**Comment by onepack** [comment]
Aug 18, 2021 10:54:33 PM Pending Payment Customer Not Notified
The user has been redirected to the following page: https://testpayv2.multisafepay.com/simulator/ideal?trxid=3732628198300389&ideal=prob&issuerid=xxxx&merchantReturnURL=https%3A%2F%2Ftestpay%2Emultisafepay%2Ecom%2Fdirect%2Fcomplete%2F%3Fmspid%3D489xxxx

**Comment by Stanislau-MultiSafepay** [comment]
Hi @onepack ,

Thank you for the report.

We assume that it happens 'cause you have _MultiSafepay_ConnectMSI_ and _MultiSafepay_CatalogInventory_ plugins enabled while all Magento 2 MSI plugins are disabled in your store. In this case, we suggest disabling _MultiSafepay_ConnectMSI_ and _MultiSafepay_CatalogInventory_ plugins and try again.

You can do it with the next CLI commands:
```
bin/magento module:disable MultiSafepay_CatalogInventory MultiSafepay_ConnectMSI
bin/magento cache:clean
```

Looking forward to your reply.

**Comment by onepack** [comment]
Hi There @Stanislau-MultiSafepay ,

This helped for the new order.
The old orders stay in the pending-payment status but as this is a dev environment it's ok. (just wanted to inform you).

Thank you!

Ps. after installing the module it seems there is a module dependency with Magento_Vault even when I do not enable this in the MSP backend settings to be used. I had to re-enable it in the modules to make the checkout work with MSP.
(https://docs.multisafepay.com/payments/integrations/ecommerce-platforms/magento2/   #module-dependencies)
