### ISSUE TITLE
Add fetch transaction info button back

### ISSUE THREAD

**Issue by thlassche** [MultiSafepay/magento2#17]
**Describe the bug**
See: https://github.com/MultiSafepay/magento2-core/pull/7

This adds back the 'Fetch' button the previous plugin did have on transaction screen in Magento.

**To Reproduce**

- Open an order
- Click transactions tab
- See that the fetch button is missing

**Expected behavior**
- Open an order
- Click transactions tab
- The fetch button is present

**Screenshots**
<img width="1932" alt="133225117-66fd771d-2984-4d37-9d5a-cfcba0696128" src="https://user-images.githubusercontent.com/2959888/133232374-be9f505a-53a5-4040-87aa-73dbc971c6d9.png">

**Comment by vinodsowdagar** [comment]
Hi @thlassche ,

I have closed the PR with some more explanation about why we are not (yet) going to add this button:
https://github.com/MultiSafepay/magento2-core/pull/7

Feel free to add a comment if you have other thoughts.

**Comment by vinodsowdagar** [comment]
Hi @thlassche , we have released a new version of our module where we implemented this feature. Clicking the button will now retrieve relevant transaction data and store it in the transaction details.

More about the latest release:
https://github.com/MultiSafepay/magento2/releases/tag/2.15.0
