### ISSUE TITLE
Checking out without postal code leads to a notice

### ISSUE THREAD

**Issue by thlassche** [MultiSafepay/magento2#18]
**Describe the bug**
When checking out without a postal code, you are not being redirect to MSP because of notice while building the address

**To Reproduce**
1. Make postal code optional for addresses in checkout
2. Checkout, chose any payment method but leave postal code empty
3. Place order

**Fix**
See https://github.com/MultiSafepay/magento2-core/pull/8

**Comment by vinodsowdagar** [comment]
Hi @thlassche ,

I have closed your PR as we have already internally reviewed and merged it.
It is available in the latest release: https://github.com/MultiSafepay/magento2/releases/tag/2.13.0

As a thank you for your contribution we would like to send you a t-shirt designed by MultiSafepay. If you are interested, could you send us your shirt size and address at integration@multisafepay.com?
