### ISSUE TITLE
Credit card component fails to render on Internet Explorer

### ISSUE THREAD

**Issue by thlassche** [MultiSafepay/magento2#19]
**Describe the bug**
On internet explorer the credit card component fails to render due to new JS syntax being used. While it might be the case that IE is not officially supported anymore (which I'd understand), in this case the fix is easy, and I created a PR with the fix: https://github.com/MultiSafepay/magento2-frontend/pull/6

**To Reproduce**
1. Use internet explorer
2. Go to checkout
3. Check console for errors

**Additional context**

**Comment by vinodsowdagar** [comment]
Hi @thlassche ,

I have closed your PR as we have already internally reviewed and merged it.
It is available in the latest release: https://github.com/MultiSafepay/magento2/releases/tag/2.13.0

As a thank you for your contribution we would like to send you a t-shirt designed by MultiSafepay. If you are interested, could you send us your shirt size and address at integration@multisafepay.com?
