### ISSUE TITLE
Error in Back-office: Cannot instantiate interface Magento\Framework\Filesystem\DriverInterface

### ISSUE THREAD

**Issue by duckchip** [MultiSafepay/magento2#2]
Hi guys,

We installed the latest version of the module (2.1.0) and got the following error when going to the General Information page (admin/system_config/edit/section/multisafepay_support)

<img width="530" alt="Screen Shot 2020-11-27 at 10 44 32" src="https://user-images.githubusercontent.com/9752966/100435389-247bef00-309e-11eb-92b1-6fd5681c9ae5.png">

`
Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Filesystem\DriverInterface in /project/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50 Stack trace: #0 /project/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #1 /project/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #2 /project/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'fileDriver', 'MultiSafepay\\Co...') #3 /project/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\Factory\Abst in /project/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50`

Module versions:

```
multisafepay/magento2                                 2.1.0                MultiSafepay module suite for Magento 2
multisafepay/magento2-adminhtml                       1.1.0                MultiSafepay module for Magento 2 (backend-only)
multisafepay/magento2-catalog-inventory               1.0.1                MultiSafepay module for Magento 2 (only for deprecated Catalog Inventory)
multisafepay/magento2-core                            2.0.0                MultiSafepay module for Magento 2
multisafepay/magento2-frontend                        1.1.0                MultiSafepay module for Magento 2 (regular frontend)
multisafepay/magento2-msi                             1.0.1                MultiSafepay module for Magento 2 (msi-only)
multisafepay/php-sdk                                  4.0.2                MultiSafepay PHP SDK
```

Magento Version: 2.3.5

Thanks in advance!

**Comment by vinodsowdagar** [comment]
Hi @duckchip ,

Thank you for your message.

We are aware of this issue and we are currently working on a fix.
We will let you know when we have found a solution for this.

**Comment by jdereus87** [comment]
I just installed the new magento2 module. Experiencing the same error described above.

Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Filesystem\DriverInterface in /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121 Stack trace: #0 /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array) #1 /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...') #2 /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...') #3 /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('MultiSafepay\\Co...') #4 /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get in /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121

The client removed all the magento MSI modules, so everything but the MSP MSI is installed. 
Magento version: 2.3.4

**Comment by vinodsowdagar** [comment]
@jdereus87 , @duckchip ,

Thank you for the feedback. 
We also noticed that some people are experiencing this issue when trying to create a transaction. 
We are working on a fix at the moment and expect to do a new release today.

**Comment by Vinod-MultiSafepay** [comment]
Hi @jdereus87 , @duckchip ,

We have created a new release which addresses this issue: https://github.com/MultiSafepay/magento2/releases/tag/2.1.1
Please let us know if the issue has been fixed for you after updating to the latest version.

**Comment by vinodsowdagar** [comment]
@duckchip , @jdereus87 ,

We have created a new release with a fix for this issue: https://github.com/MultiSafepay/magento2/releases/tag/2.1.1
Please let us know if updating to the latest version fixed the issue for you.

**Comment by duckchip** [comment]
@Vinod-MultiSafepay can you update packagist please? The new tag is missing. https://packagist.org/packages/multisafepay/magento2
Thx!

**Comment by vinodsowdagar** [comment]
Hi @duckchip ,

Packagist didn't automatically update this time. 
I manually updated it and it should be fine now.

Can you try again?

**Comment by duckchip** [comment]
bug seems fixed. 

Thanks @Vinod-MultiSafepay!
