### ISSUE TITLE
Frontend fetches API tokens for CC component, while payment type is configured as redirect

### ISSUE THREAD

**Issue by thlassche** [MultiSafepay/magento2#22]
**Describe the bug**
This PR describes and solves it: https://github.com/MultiSafepay/magento2-frontend/pull/8

**To Reproduce**
1. Enable a credit card payment method (e.g. Amex)
2. Set its payment type to redirect

**Expected behavior**
No short-lived API tokens are fetched from MSP's API's

**Comment by vinodsowdagar** [comment]
Hi @thlassche ,

Thank you for reporting this issue.

The provided change has been released in the latest version:
https://github.com/MultiSafepay/magento2-internal-frontend/releases/tag/1.13.0
