### ISSUE TITLE
Notice: Undefined index: edencom_categories in vendor/multisafepay/magento2-core/Model/Ui/Giftcard/EdenredGiftcardConfigProvider.php on line 88

### ISSUE THREAD

**Issue by mdevrees** [MultiSafepay/magento2#24]
**Describe the bug**
Magento 2.4.3-p1  
A magento upgrade with `composer require multisafepay/magento2-core` resulted in this error. No further configuration, just module install, added a product to cart and try to navigate to cart.

**To Reproduce**
1. Install the module without any config to a magento 2.4.3-p1 instance
2. Add a product to cart
3. Navigate to checkout/cart
4. Error pops up

**Expected behavior**
Cart is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/1950480/139681044-31f7886b-4ab7-4fc3-a102-b2ad4c4186a3.png)
(output of module yireo/magento2-whoops)

**Desktop (please complete the following information):**
 Linux Mint 20.2
 Firefox 93.0

**Additional context**
`if ($ids = $this->getPaymentConfig($storeId)[$couponCode . '_categories']) {` probably does not check for undefined indexes, wrapping it in isset() before defining `$ids` will do the trick.

**Comment by vinodsowdagar** [comment]
Hi @mdevrees ,

This issue only happens with the release that was done this morning. 
We have just released a hotfix that should fix this issue: 
https://github.com/MultiSafepay/magento2/releases/tag/2.14.1

Could you update the module and try again?

**Comment by mdevrees** [comment]
Hi @Vinod-MultiSafepay 
Thanks for the quick reply. The update seems to resolve the issue. Thanks!
