### ISSUE TITLE
Order stays on pending payment

### ISSUE THREAD

**Issue by jdereus87** [MultiSafepay/magento2#25]
**Describe the bug**
Order stays on Pending Payment in local dev environment. 

**To Reproduce**
1. Entered test api key
2. Enabled iDeal
3. Order a product
4. After submit it forwards to the MSP testmerchant environment. 
5. Select 'Complete'
6. It returns to the success page. 

**Expected behavior**
Order should be on 'processing' instead of 'pending payment'. Full amount is still due.

**Desktop (please complete the following information):**
Magento 2.3.5-p1.
MSP 2.14.2

**Additional context**
MSI is disabled. I have installed the full package through composer. ConnectMSI is disabled.
I have tried enabling/disabling ConnectCatalogInventory. Does not seem to make a difference.

MSP log entry:
[2021-11-04 15:25:29] MultiSafepay.DEBUG: (Order ID: 2000000380) User redirected to the following page: https://testpayv2.multisafepay.com/simulator/ideal?trxid=4442569319105622&ideal=prob&issuerid=0021&merchantReturnURL=https%3A%2F%2Ftestpay%2Emultisafepay%2Ecom%2Fdirect%2Fcomplete%2F%3Fmspid%3D5087765 [] []
[2021-11-04 15:25:34] MultiSafepay.DEBUG: (Order ID: 2000000380) User redirected to the success page. [] []

Am I missing something? If not, where can I start to debug this?

**Comment by vinodsowdagar** [comment]
Hi @jdereus87 ,

This is normal behaviour on a local environment. 
We work with web-hooks on custom Magento 2 controllers that trigger all the actions needed to, among other things, create an invoice and set the order to the 'processing' state.

Our payment platform can not find your local environment and therefore the actions are not triggered. To still be able to test on a local environment, you can call the same url that is used as the web-hook directly via the browser.

Login to your MultiSafepay Account, navigate to Transactions > Transaction overview > Choose a transaction which was created on your local environment > Go to offline actions > Click on the link icon.

![image](https://user-images.githubusercontent.com/53818758/140371655-22b1b2f2-106d-4530-8203-ce30992ac1ee.png)

You will see a link, which is the url you can copy and paste into your browser and navigate to. If everything works correctly, you should see an 'ok' as a text response. After that you can go back to the Magento order and you will see that all the actions have been triggered.

Please let me know if this method worked for you.

**Comment by eperrotta** [comment]
Hello @Vinod-MultiSafepay,
unfortunately not always the link is present.
Several tests I conducted on testing instances do not display the link
![image](https://user-images.githubusercontent.com/5153895/141133820-7f273d2b-a553-4869-875f-d91a7e9bcb05.png)

Moreover, whenever the order falls into "Pending Payment" state, it seems there's no action possible to turn the order into Processing.

**Comment by vinodsowdagar** [comment]
Hi @eperrotta ,

If the above option is not working for you, you can always try to create and trigger the url manually as follows:
{{base_url}}/multisafepay/connect/notification?transactionid=123456&timestamp=12345678 where the {{base_url}} is your default store url. The transactionid is your order id and the timestamp can be any number for test transactions.

See more about how to handle payment notifications on the following docs page:
https://docs.multisafepay.com/developer/api/notification-url/

**Comment by vinodsowdagar** [comment]
@eperrotta Were you able to sort this out? When the link is not displayed, it means that the transaction is still pending. Sometimes it can have a delay on our test environment on busy days.

**Comment by vinodsowdagar** [comment]
@eperrotta I am closing this again due to inactivity. If you have any more problems related to this, please reopen this issue or send an e-mail to integration@multisafepay.com

**Comment by onepack** [comment]
Can you please re-open this case? I have exactly the same issue with a customer.
It is a live webshop and not a localhost environment.
All orders stay Pending and no amount is captured until I copy the link from the MSP backend order, where the status is Complete, and paste this in the browser address.
It is not until that action that the order completes.

GET, POST etc is enabled on the server which I checked and tested via Postman.

Magento ver. 2.4.3-p1
MSP 2.17.0
