### ISSUE TITLE
Validate API key button uses default store view always

### ISSUE THREAD

**Issue by thlassche** [MultiSafepay/magento2#26]
**Describe the bug**
Pressing validate API key always yields a check for store id = 0 instead of the storeview of the current selected scope

**To Reproduce**
1. Leave API key on default store view empty
2. Go to a non default storeview configuration
2. Enter a valid API key
3. Click validate API key
4. Error is shown stating the API key is invalid

**Expected behavior**
The API key is shown as valid

**Cause**
https://github.com/MultiSafepay/magento2-adminhtml/blob/master/Controller/Adminhtml/Api/Validate.php#L87 is using a `store_id` parameter, but that parameter is not passed here: 
https://github.com/MultiSafepay/magento2-adminhtml/blob/master/Block/Adminhtml/Config/ValidateApiKeyButton.php#L72

**Comment by vinodsowdagar** [comment]
Hi @thlassche ,

Good observation, it seems to be correct. We will look into this and let you know more as soon as we have figured it out.

**Comment by vinodsowdagar** [comment]
Hi @thlassche ,

We have fixed this issue in our latest release:
https://github.com/MultiSafepay/magento2/releases/tag/2.16.0

I am closing this issue. If you still have questions or comments, feel free to reopen this.
