### ISSUE TITLE
Allow setting a separate order status for partially refunded orders, just like in Magento 1

### ISSUE THREAD

**Issue by hd-jeroen** [MultiSafepay/magento2#27]
**Is your feature request related to a problem? Please describe.**
When an order is partially refunded, it would be nice to be able to display a separate order status which shows that an order is partially refunded. This also works better for accounting software used by webshops, plus the merchant can easily see that an order is partially refunded.

**Describe the solution you'd like**
Create configuration settings which allow specifying a separate order status for partially refunded orders, just like the way it used to be in Magento 1.

**Describe alternatives you've considered**
N/A

**Additional context**
In Magento 1 this was available in the configuration:
![image](https://user-images.githubusercontent.com/80255844/145007429-b75ea2c9-fd4b-4ad2-9e39-a0357eccda3e.png)

**Comment by vinodsowdagar** [comment]
Hi @dehaan-jeroen ,

Thank you for your request, i have created a backlog task for this.
As soon as i have more updates about the development of this feature, i will let you know.

**Comment by vinodsowdagar** [comment]
Hi @dehaan-jeroen ,

We have released a new version of our module with your feature request in it:
https://github.com/MultiSafepay/magento2/releases/tag/2.16.0

I am closing this issue. If you have questions or comments, feel free to reopen this. We will update our documentation accordingly soon!
