### ISSUE TITLE
multisafepay/magento2-core breaks swagger

### ISSUE THREAD

**Issue by dimasalamatov** [MultiSafepay/magento2#29]
**Describe the bug**
Swagger is not working after multisafepay/magento2-core module is installed.

**To Reproduce**
1. Go to /swagger
2. See the error "Failed to load API definition."
![image](https://user-images.githubusercontent.com/23279929/147239357-e93611fa-062f-4062-aa03-efc1499738a1.png)
3. Check /rest/all/schema?services=all
4. See the explanation of the error
![image](https://user-images.githubusercontent.com/23279929/147239597-5ec91542-0174-4279-8bfc-2741a8bd997c.png)

**Expected behavior**
Swagger works properly.

**Additional info**
Seems swagger can not recognize return types which is not full path to class / interface.
![image](https://user-images.githubusercontent.com/23279929/147239959-77434748-c8a2-4293-9406-62e1e14c52c8.png)

In case full path is specified, swagger will work properly.
![image](https://user-images.githubusercontent.com/23279929/147240065-40cf44b6-51e8-455b-8b38-86d1b5eafd99.png)

**Extension info**
1. Name: **multisafepay/magento2-core**
2. Version: **2.13.0**

**Comment by vinodsowdagar** [comment]
Hi @dimasalamatov ,

Thank you for the report!
I have created a backlog item for us to check it out. I expect to pick it up next week.

When i know more about the status of our investigation i will let you know.

**Comment by vinodsowdagar** [comment]
Hi @dimasalamatov ,

We have fixed this issue in our latest release:
https://github.com/MultiSafepay/magento2/releases/tag/2.16.0

I am closing this issue. If you still have questions or comments, feel free to reopen this issue.
