### ISSUE TITLE
Order saving error: Type "" is not a known type.

### ISSUE THREAD

**Issue by LucasMDL** [MultiSafepay/magento2#3]
Using Magento 2.4.0 and multisafepay/magento2 2.2.1.

When creating an order via the backend, using a Magento delivery method, the following error occurs;
`Order saving error: Type "" is not a known type. Available types: direct, redirect,paymentlink.`

**Comment by vinodsowdagar** [comment]
Hi @LucasMDL ,

We have succesfully reproduced this issue and we will include a fix in the next release.
We will keep you updated when the fix will be available.

**Comment by vinodsowdagar** [comment]
Hi @LucasMDL ,

We have released a new version of our extension with a fix for this issue:
https://github.com/MultiSafepay/magento2/releases/tag/2.2.0

Please update with the following command: 
`composer update multisafepay/magento2 --with-dependencies`
