### ISSUE TITLE
Magento 2.4.4 support

### ISSUE THREAD

**Issue by JonathanBBD** [MultiSafepay/magento2#31]
**Describe the bug**
Requirement `php-http/guzzle6-adapter` of subpackage `multisafepay/magento2-core` is incompatible with magento 2.4.4

On `composer require magento/product-enterprise-edition:2.4.4` we get the errors `php-http/guzzle6-adapter v2.0.2 requires guzzlehttp/guzzle ^6.0`.
The package `multisafepay/magento2-core` is using `php-http/guzzle6-adapter` which in turn requires `guzzlehttp/guzzle ^6.0`. Except Magento requires version 7, see `magento/product-community-edition 2.4.4 requires guzzlehttp/guzzle ^7.3.0`.

**To Reproduce**
1. Try to install either `composer require magento/product-enterprise-edition:2.4.4` or `composer require magento/product-community-edition:2.4.4` (but community isn't released at the moment, try using the released enterprise instead)

**Expected behavior**
Magento is installed.
( I could not check PHP 8.1 compatible )

**Screenshots**

Composer require output.

```
[...]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - multisafepay/magento2 2.7.0 requires multisafepay/magento2-core 2.5.1 -> satisfiable by multisafepay/magento2-core[2.5.1].
    - multisafepay/magento2 2.7.0 requires multisafepay/magento2-core 2.5.1 -> satisfiable by multisafepay/magento2-core[2.5.1].
    - multisafepay/magento2 2.7.1 requires multisafepay/magento2-core 2.5.2 -> satisfiable by multisafepay/magento2-core[2.5.2].
    - multisafepay/magento2 2.7.1 requires multisafepay/magento2-core 2.5.2 -> satisfiable by multisafepay/magento2-core[2.5.2].
[...]
    - php-http/guzzle6-adapter v2.0.0 requires php ^7.1 -> your PHP version (8.1.4) does not satisfy that requirement.
    - php-http/guzzle6-adapter v0.3.1 requires php-http/httplug 1.0.0-beta -> satisfiable by php-http/httplug[v1.0.0-beta] but these conflict with your requirements or minimum-stability.
    - php-http/guzzle6-adapter v0.3.0 requires php-http/httplug 1.0.0-beta -> satisfiable by php-http/httplug[v1.0.0-beta] but these conflict with your requirements or minimum-stability.
    - php-http/guzzle6-adapter v0.2.1 requires php-http/httplug 1.0.0-beta -> satisfiable by php-http/httplug[v1.0.0-beta] but these conflict with your requirements or minimum-stability.
    - php-http/guzzle6-adapter v0.2.0 requires php-http/httplug 1.0.0-alpha3 -> satisfiable by php-http/httplug[v1.0.0-alpha3] but these conflict with your requirements or minimum-stability.
    - Conclusion: remove guzzlehttp/guzzle 7.4.2
    - Conclusion: don't install guzzlehttp/guzzle 7.4.2
    - Conclusion: remove magento/product-enterprise-edition 2.4.4
    - Conclusion: don't install guzzlehttp/guzzle 7.4.1
    - Conclusion: don't install guzzlehttp/guzzle 7.4.0
    - Conclusion: don't install guzzlehttp/guzzle 7.3.0
    - Conclusion: don't install guzzlehttp/guzzle 7.4.2
    - Conclusion: don't install guzzlehttp/guzzle 6.5.4
    - Conclusion: don't install guzzlehttp/guzzle 7.4.1
    - magento/product-community-edition 2.4.4 requires guzzlehttp/guzzle ^7.3.0 -> satisfiable by guzzlehttp/guzzle[7.4.2, 7.3.0, 7.4.0, 7.4.1].
    - Conclusion: don't install guzzlehttp/guzzle 7.4.0
```

**Desktop (please complete the following information):**
 -

**Smartphone (please complete the following information):**
-

**Additional context**
Please check https://github.com/php-http/guzzle7-adapter, looks like a drop-in replacement but requires PHP up to ^8.0 instead up to ^8.1 .

**Comment by vinodsowdagar** [comment]
Hi @JonathanBBD ,

Thank you for the report.
I have created a task to look into this as soon as possible.

We expect to have a solution for this by the end of next week.
I will keep you informed about the progress of this issue in the meantime.

**Comment by JonathanBBD** [comment]
If it might save you time.

Magento 2.4.4 officially supports php 8.1 with this release, but our project is still running php 7.4 due other vendors being incompatible. When the drop-in solution is working for php 7, it would already be a usable commit to our project.

**Comment by JonathanBBD** [comment]
Hi @Vinod-MultiSafepay ,

We would like to rollout Magento 2.4.4, but the nature of the plugin blocks the project. Any progress ?

**Comment by vinodsowdagar** [comment]
Hi @JonathanBBD ,

Due to the different adapters that are needed for Psr17 and Psr18 implementation, we have been working on a change that removes the dependency on Guzzle entirely, since we had to make sure to still be backwards compatible with Guzzle 6 as well as Guzzle 7, which complicated it a bit.

This change will make it so that our modules will use the native Curl client from the Magento framework instead. It takes a bit longer this way, because the native Curl client is far from perfect, but it at least ensures that we are not dependant on an external HTTP Client like Guzzle anymore.

It is currently internally in review and i expect to do a new release at the beginning of next week.

**Comment by JonathanBBD** [comment]
Hi @Vinod-MultiSafepay ,

At first, thank you for your fast reply. I'm happy to know you are working on it. Sounds like a good decision.

**Comment by henk-hypershop** [comment]
Any update on the 2.4.4 compatibility yet?

**Comment by danielcivit** [comment]
Hi @hypershopbv 

Our apologies for the previous false notice, in which we commented that we would release this version this week. 
We have found some bugs to fix in the code review process, and some of our developers have reported sick this week, so we are a little behind from the initial estimated released date. 

We will get back to you as soon as possible. 
Thanks again for your report and interest.

**Comment by deadlyw1re** [comment]
Any update on the 2.4.4 compatibility yet?

**Comment by vinodsowdagar** [comment]
Hi @JonathanBBD , @hypershopbv , @deadlyw1re ,

We have just released a new version which brings compatibility with version 2.4.4:
https://github.com/MultiSafepay/magento2/releases/tag/2.17.0

If you encounter any problems, please let us know and we will look into it.

**Comment by JonathanBBD** [comment]
Hi @Vinod-MultiSafepay ,

Thanks for the notification! I will check it out tomorrow.

**Comment by vinodsowdagar** [comment]
Hi @JonathanBBD 
I assume that everything is working as it should now. 
If not, feel free to add a comment or open a new issue.

For now i am closing this one due to inactivity.
