### ISSUE TITLE
Missing functions from old module

### ISSUE THREAD

**Issue by JoostWan** [MultiSafepay/magento2#4]
I see some functions are missing. When this functions will be added? Like;

- E-mail invoice to customer
- Keep cart alive (Or is this default enabled? Don't see this option in the backend like old module)

**Comment by vinodsowdagar** [comment]
Hi @JoostWan ,

E-mail invoice to customer is implemented here as well. For this we are currently looking at the Yes/No value of the following configuration field to decide if the invoice e-mail should be sent or not: Stores > Configuration > Sales > Sales Emails > Invoice > Enabled
We understand this is a bit confusing so we are going to implement our own configuration field in the next update just like we had before.

The 'keep cart alive' function was not efficiently implemented in the old module, so we are currently looking at a better way to do this. We expect to add it in the following update as well.

We will let you know when this feature will be available.

**Comment by vinodsowdagar** [comment]
Hi @JoostWan ,

We have introduced a dedicated article which explains most of the important differences between the deprecated and the new module. Hopefully this will give you more insight in the changes that have been made:
https://docs.multisafepay.com/integrations/ecommerce-integrations/magento2/faq/migrating-to-new-plugin/

For now i will close this issue. If you have more questions, please re-open this issue or create a new one.

**Comment by akosglue** [comment]
Hi, I have a question w.r.t. the old module. We could add a column to the sales overview: multisafepay status. That was useful to see if the order was paid. Is that also possible in the new version (or something similar)?

**Comment by vinodsowdagar** [comment]
Hi @akosglue ,

This feature has not yet been implemented inside the new MultiSafepay Magento 2 plugin, due to low demand. But i have put it on the backlog now. As soon as this feature has been released, we will let you know.
