### ISSUE TITLE
Translation not working for error messages

### ISSUE THREAD

**Issue by mlaurense** [MultiSafepay/magento2#44]
**Describe the bug**
Due to line wrapping, there are now multiple spaces/tabs in translatable strings, causing the translation to fail. Following is one example, but there could be more

**To Reproduce**
See for example `vendor/multisafepay/magento2-core/Observer/OrderPlaceAfterObserver.php`:
- Line 88/89
- Line 93/94
- Line 99/100
- Line 104/105

**Expected behavior**
A correctly translatable string

**Screenshots**
![Schermafbeelding 2022-12-21 om 14 48 44](https://user-images.githubusercontent.com/16759472/208921178-2ff6e8b6-abec-446b-b06b-8de5f993dcfc.png)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
N/A

**Comment by mlaurense** [comment]
Seems to be broken for quite some time as well...
https://github.com/MultiSafepay/magento2-core/commit/7620e0cf130b243f0c2880ebd486bbe1dfcc1f49#diff-f2c6469b7804cf35fc1119238526965427a0d96d87cda4037d865a33d389da3f

**Comment by vinodsowdagar** [comment]
Hi @mlaurense ,

Thank you for the report.
We are going to look into this and come back to you later this week.

**Comment by vinodsowdagar** [comment]
Hi @mlaurense ,

The fix for this will be added in the next release, we will give you an update when the next release has been done.

**Comment by vinodsowdagar** [comment]
Hi @mlaurense ,

We have released a new version of the module with the fix in it: https://github.com/MultiSafepay/magento2/releases/tag/2.23.0

I'm closing this one for now, if you have more questions or comments, feel free to add a comment here or create a new issue.
