### ISSUE TITLE
Afterpay / Riverty not working in combination with MagePlaza OSC

### ISSUE THREAD

**Issue by GuidoHub** [MultiSafepay/magento2#45]
**Describe the bug**
Getting a javascript error in Mageplaza checkout when Afterpay is enabled as payment in checkout. According to your documentation  https://docs.multisafepay.com/docs/magento-2 it should be compatible.

[ERROR] Failed to load the "MultiSafepay_ConnectFrontend/js/view/payment/gateway/method-renderer/afterpay" component.

The problem is caused by getting phonenumber of shippingAddress. Check file https://github.com/MultiSafepay/magento2-frontend/blob/master/view/frontend/web/js/view/payment/gateway/method-renderer/afterpay.js on row 62.

When I change row 54 to return quote.shippingAddress().telephone I have no problems.

**To Reproduce**
1. add product to cart
2. Go to checkout
3. See error in console (javascript)

**Expected behavior**
I would expect that payment option Afterpay would be visible

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**
- Magento 2.4.5-p1
- Mageplaza OSC 4.1.3

**Comment by vinodsowdagar** [comment]
Hi @GuidoHub ,

Thank you for the report.
We are going to try to reproduce this issue and come back to you later with an update.

**Comment by danielcivit** [comment]
Hi @GuidoHub 

We have released a new version of the module (v3.1.0) which fixes the reported issue.

I'm closing this one for now. 

If you still find any problems, please let us know by replying to this issue or by creating a new one.
