### ISSUE TITLE
Payment methods missing after cancelled order

### ISSUE THREAD

**Issue by accentinteractive** [MultiSafepay/magento2#47]
**Describe the bug**
When customers as guest return during checkout without a successful payment, we see that various payment methods are no longer visible at the checkout. Payment methods that are available for all customer groups will remain visible, but payment methods for specific customer groups will no longer be visible.

**To Reproduce**
1. Enable different MSP Payment methods
2. Set 'Guest' and 'General' for 'Specific Customer Groups' for one or multiple methods
3. Add a product to the cart as a guest
4. Go to the checkout
5. You see all payment methods
6. On the MSP payment page select 'Cancelled' as status
7. Return to the shop
8. Go back to the checkout

**Expected behavior**
Payment methods that are visible for guests are still visible the second time.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 109.0.5414.87

- Magento version: 2.4.4-p2
- PHP: 8.1
- MultiSafepay version: 2.22.0

**Additional context**
There is a difference inside `\MultiSafepay\ConnectCore\Gateway\Validator\CustomerGroupValidator::validate` when visiting the checkout for the second time. The value from `$quote->getCustomerGroupId()` is different.

First time visiting the checkout I see that the quote field 'customer_group_id' = '0'. But the second time the value is different ('customer_group_id' = 'null).

**Comment by danielcivit** [comment]
Hello @accentinteractive.

We will look into this issue and get back to you with more information.

Thanks for your report.

**Comment by vinodsowdagar** [comment]
Hi @accentinteractive ,

We could reproduce the issue and are working on a fix.
It is expected to be included in the next release.

I'll let you know when there is an update.

**Comment by vinodsowdagar** [comment]
Hi @accentinteractive  ,

We have released a new version of the module with the fix in it: https://github.com/MultiSafepay/magento2/releases/tag/2.23.0

I'm closing this one for now, if you have more questions or comments, feel free to add a comment here or create a new issue.

**Comment by davekleijn** [comment]
Thanks @Vinod-MultiSafepay!
