### ISSUE TITLE
Second chance email is not send.

### ISSUE THREAD

**Issue by bhavinxelcomm** [MultiSafepay/magento2#5]
i cant get second chance email for payment after i missed payment for order with testmultisafe account.
How can i auto send email after i missed order payment.. have any idea??

**Comment by vinodsowdagar** [comment]
Hi @bhavinxelcomm ,

Did you make sure you turned Second Chance on for your website inside MultiSafepay Control?

You can find the steps on how to turn on Second Chance on the following page:
https://docs.multisafepay.com/tools/second-chance/how-to-enable-second-chance/

**Comment by bhavinxelcomm** [comment]
Thanks for reply,

I set config from this link but some how event is not fire so i am finding
solution. if you have another way to solve??

**Comment by vinodsowdagar** [comment]
@bhavinxelcomm ,

Please send an e-mail to our integration team via integration@multisafepay.com, so our integration specialists can help you further.
