### ISSUE TITLE
[2.4.4-2.4.5] Customer group is set to null by Magento on guest orders

### ISSUE THREAD

**Issue by Hexmage** [MultiSafepay/magento2#51]
**Describe the bug**
In Magento 2.4.4-2.4.5 because of a Magento bug when an order is placed the Customer Group is set to `null` on a quote. If you restore a quote, because you canceled the order in MSP, payment methods might disappear because they can be set to only show for specific customer groups and `null` will never match. This only affects 2.4.4 and 2.4.5, and is fixed in Magento 2.4.6.

**To Reproduce**
1. Set a MSP Payment method to only work for specific customer groups, one of these groups should be `not logged in`
2. Place a guest order and cancel it in MSP.
3. The Payment method configured at 1. now disappears.

**Potential fix**
If Customer Group 0 is in the allowed groups array also match on null. (Or suggest to people to upgrade to 2.4.6 but we all know this isn't always an option).

**Comment by vinodsowdagar** [comment]
Hi @Hexmage ,

Thank you for your report.
Can you confirm that your issue is the same as this one: https://github.com/MultiSafepay/magento2/issues/47 ?
If so, it seems we have already fixed this in version 2.23.0

**Comment by Hexmage** [comment]
Yes, that's the identical issue.

**Comment by danielcivit** [comment]
> Yes, that's the identical issue.

Hi @Hexmage.

I am closing this ticket. Like @Vinod-MultiSafepay mentioned, the Magento bug was handle in [2.23.0](https://github.com/MultiSafepay/magento2/releases/tag/2.23.0).
