### ISSUE TITLE
Not compatible with multisafepay/magento2-graphql

### ISSUE THREAD

**Issue by PascalBrouwers** [MultiSafepay/magento2#52]
Version 3.0.0 is not compatible with multisafepay/magento2-graphql

See: https://github.com/MultiSafepay/magento2-graphql/issues/6

```
Problem 1
    - multisafepay/magento2-graphql 3.2.0 requires multisafepay/magento2-frontend ^1.19 -> satisfiable by multisafepay/magento2-frontend[1.19.0].
    - multisafepay/magento2-graphql 3.1.0 requires multisafepay/magento2-frontend ^1.18 -> satisfiable by multisafepay/magento2-frontend[1.18.0, 1.18.1, 1.18.2, 1.19.0].
    - multisafepay/magento2-graphql 3.0.0 requires multisafepay/magento2-frontend ^1.17 -> satisfiable by multisafepay/magento2-frontend[1.17.0, ..., 1.19.0].
    - You can only install one version of a package, so only one of these can be installed: multisafepay/magento2-frontend[1.17.0, ..., 1.19.0, 2.0.0].
    - multisafepay/magento2 3.0.0 requires multisafepay/magento2-frontend 2.0.0 -> satisfiable by multisafepay/magento2-frontend[2.0.0].
    - Root composer.json requires multisafepay/magento2 ^3.0 -> satisfiable by multisafepay/magento2[3.0.0].
    - Root composer.json requires multisafepay/magento2-graphql ^3.0 -> satisfiable by multisafepay/magento2-graphql[3.0.0, 3.1.0, 3.2.0].
```

**Comment by vinodsowdagar** [comment]
Hi @PascalBrouwers ,

That is correct, the GraphQL module will receive compatibility with the latest major version a bit later. We are currently still working on that.

We will keep you updated.

**Comment by PascalBrouwers** [comment]
Ah ok, any idea when? Your support mentioned we needed to upgrade to the 3.0 version but we can't because it does not have graphql support.

**Comment by danielcivit** [comment]
Hi @PascalBrouwers.

Thanks for contact us. We just released a new version solving this issue. Now you should be able to install multisafepay/magento2-graphql module using the latest version of the modules that belongs to the [meta package](https://github.com/MultiSafepay/magento2).

We are closing this ticket now, but if you have any other question or feedback, please, reopen this ticket.
