### ISSUE TITLE
multisafepay/connect/notification request is returning 302 error

### ISSUE THREAD

**Issue by javimi93** [MultiSafepay/magento2#53]
**Describe the bug**
Request "multisafepay/connect/notification" is returning 302 error

**To Reproduce**
1. Place an order
2. I see this log on access.log: 185.99.129.254 - - [18/May/2023:14:09:12 +0200] "POST /fr/multisafepay/connect/notification?transactionid=2000029590&timestamp=1684411752 HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101\x22)" "-"
3. Order keeps in pending payment

**Expected behavior**
Order would pass to processing status

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
- Magento 2.4.5-p2
- multisafepay/magento2: 2.1.0

**Comment by danielcivit** [comment]
Hi @javimi93 

Thanks for contact us. 

We don't have this kind of report from anyone else at this moment, and according to your report you are using the 2.1.0 version of our module, which was released two and half years ago. 

Could you upgrade to the latest version and let us know if this issue still happens?

**Comment by javimi93** [comment]
Hi @Daniel-MultiSafepay ! I've upgraded to 3.1.0 and same result. I didn't mention it but this happens on test mode.

In our production environment (2.1.0 version) it is working.

Other than that, when I execute the notification url in the browser (GET), it works, so it must be something related to POST request.

Regards!

**Comment by danielcivit** [comment]
> "but this happens on test mode."

It seems to me that what you mean is that this happens on your **staging server**, not in test mode, which in our module is a setting field that you can use to process transactions and payments in our sandbox environment.

Is clear to me, if this is happening in one place, and not in the other, is something related to your environment and not to the module itself.

Here, in GitHub, is not a good place to share sensitive information, like your URLs, etc.  Could you share with me your email address, or send us an email with a reference to this GitHub issue to support@multisafepay.com

That way, we can transfer this conversation to our support ticket system, and hopefully, with more information, we will find the reason of what's happening in your environment.

**Comment by danielcivit** [comment]
Hi @javimi93.

I'm closing this ticket due to inactivity. Please, re-open it if this is still an issue for you.
