### ISSUE TITLE
Latest versions are no longer compatible with Magento 2.3.x (SecureHtmlRenderer)

### ISSUE THREAD

**Issue by hostep** [MultiSafepay/magento2#55]
**Describe the bug**
The latest versions of this module [use a class `Magento\Framework\View\Helper\SecureHtmlRenderer`](https://github.com/MultiSafepay/magento2-adminhtml/blob/e601d110f90585d2135113964fc11e7585547362/Block/Adminhtml/Form/Field/CreditCardIconRadios.php#L59) which was introduced in [Magento 2.4.0](https://github.com/magento/magento2/blob/2.4.0/lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php) and didn't exist yet [in 2.3.x](https://github.com/magento/magento2/blob/2.3.7-p4/lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php)

This leads to crashes in Magento 2.3.x shops.

**To Reproduce**
1. Install Magento 2.3.6-p1
2. Install this MultiSafepay module at version 3.1.1
3. Run `bin/magento setup:di:compile`

**Expected behavior**
No errors

**Actual output**
```
$ bin/magento setup:di:compile
Compilation was started.
Area configuration aggregation... 5/8 [=================>----------]  62% 47 secs 240.0 MiB
In ClassReader.php line 43:

  Class Magento\Framework\View\Helper\SecureHtmlRenderer does not exist
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: N/A
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: N/A

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: N/A
 - OS: [e.g. iOS8.1]: N/A
 - Browser [e.g. stock browser, safari]: N/A
 - Version [e.g. 22]: N/A

**Additional context**

**Comment by vinodsowdagar** [comment]
Hi @hostep ,

Thanks for this one, i created a backlog item for it already. I'll let you know when we have looked into it a bit more.

**Comment by vinodsowdagar** [comment]
Hi @hostep ,

We've confirmed the issue and will make the fix available in a new release. We'll keep you informed.

**Comment by vinodsowdagar** [comment]
Hi @hostep ,

We've introduced a new release where this issue has been fixed:
https://github.com/MultiSafepay/magento2/releases/tag/3.1.2

I'm closing this issue for now. 
Please add a new comment if there are any related comments and we will reopen this if needed.
