### ISSUE TITLE
Order doesn't change status

### ISSUE THREAD

**Issue by vacla** [MultiSafepay/magento2#57]
**Describe the bug**
Order is still pending while in the log files it says it is completed and processing

**To Reproduce**
1. Create a order in magento
2. Go to backend and see wrong status

**Expected behavior**
The order is processing

**Screenshots**
Magento backend:
![Screenshot from 2023-08-14 09-06-21](https://github.com/MultiSafepay/magento2/assets/10290022/af3ac298-8f22-433e-8ac5-ee7a8a4a4875)
Database:
![Screenshot from 2023-08-14 09-08-33](https://github.com/MultiSafepay/magento2/assets/10290022/7c9a0b91-d175-426c-9c34-480b22d7cc0b)
Logs:
![Screenshot from 2023-08-14 09-11-06](https://github.com/MultiSafepay/magento2/assets/10290022/56b072ab-bc76-4c43-8bc6-097bfa289a91)

Magento version: 2.4.5-p4
Multisafepay: 3.1.2

**Desktop:**
 - OS: Linux
 - Browser: Chrome
 - Version 115.0.5790.170 (Official Build) (64-bit)

**Comment by vinodsowdagar** [comment]
Hi @vacla ,

Can you send the debug logs to integration@multisafepay.com?

Please download the zip package through admin: Stores > Configuration > MultiSafepay > General Settings > General Settings > MultiSafepay payment logs

Please also refer to this Github ticket, so my colleagues know what this is about.

**Comment by vacla** [comment]
@Vinod-MultiSafepay We have sent the info accordingly to email now.

**Comment by vinodsowdagar** [comment]
Hi @vacla ,

I've heard from my colleagues that the issue has already been resolved through e-mail.
I'm closing this one.
