### ISSUE TITLE
Apple pay payment not visible

### ISSUE THREAD

**Issue by Naberdz** [MultiSafepay/magento2#60]
**Describe the bug**
Apple pay payment method is not visible

**To Reproduce**
Enable payment option in backend.

**Expected behavior**
We should see apple pay payment method in checkout.

**Screenshots**
<img width="975" alt="Schermafbeelding 2023-10-26 om 15 33 03" src="https://github.com/MultiSafepay/magento2/assets/37579149/c0bdf90d-8ce2-4fa8-83aa-318713a48f9f">
<img width="872" alt="Schermafbeelding 2023-10-26 om 15 32 54" src="https://github.com/MultiSafepay/magento2/assets/37579149/3ccacbb4-f98b-42f5-b525-ec34f1dd0f17">

Tested in different browsers / devices

**Desktop (please complete the following information):**
Mac os
Chrome v 118.0.5993.88 
Safari v 16.6.1

**Smartphone (please complete the following information):**
Iphone 13 PRO

On the magento 1 installation everything works fine with the same API key ( magento 2 is still in development )

**Comment by vinodsowdagar** [comment]
Hi @Naberdz ,

Thank you for the report.

For Apple Pay to be visible there are a lot of different constraints. Some examples are:

- The website needs to use an SSL certificate and be served through HTTPS, HTTP will be considered insecure for use with Apple Pay
- The browser needs to support the Apple Pay JS API
- The device needs to be logged in with an active Apple (iCloud) account
- The device needs to have Apple Pay Wallet enabled
- The device needs to have a valid Debit or Credit card added in the Apple Pay wallet
- The device needs to have a valid billing address assigned to the card with which you want to pay
- The device needs to be in the list of supported countries

...and more constraints. For all of them, please refer to the Apple Pay docs.

If you want to test completing a payment with Apple Pay on the MultiSafepay test environment, please create an Apple Pay Sandbox account.

I'm closing this issue in the meantime. If it's still not working, feel free to add a new comment and we will reopen it.

**Comment by Naberdz** [comment]
Hallo Vinod.

indeed it works different than magento1 module version.
in magento1 version we have this payment method in the desktop chrome browser.

enabling SSL and using safari does solve the issue.
