### ISSUE TITLE
wrong shipping cost when zero tax 

### ISSUE THREAD

**Issue by vshatylo** [MultiSafepay/magento2#62]
**Describe the bug**
We experience an issue that total paid amount is different between magento and multisafepay

**Pre-conditions**
 - configure tax rules to provide zero tax value by filled valid VAT Number 
 - prices on website and cart page should be "Excluding Tax"
 - VAT Number should be available to fill on the checkout page

**To Reproduce**
1. add product to the basket 
2. go to checkout 
3. fill shipping address and Valid VAT number
4. choose shipping method with price greater than zero
5. place an order using MultiSafePay payment method

**Expected behavior**
Shipping cost is the same in Magento and MultiSafepay. Customer pays equal price.

**Additional context**
Magento Version: 2.4.6-p3
MultiSagePay version: 3.4.0

**Comment by vinodsowdagar** [comment]
Hi @vshatylo ,

Thank you for the report, we'll look into it and come back to you later.

**Comment by vinodsowdagar** [comment]
Hi @vshatylo ,

We could successfully reproduce this issue and we will be working on a fix in the upcoming sprint. If there are questions in the meantime, please let us know.

**Comment by vinodsowdagar** [comment]
Hi @vshatylo ,

We've updated the module with a change that should fix your issue: https://github.com/MultiSafepay/magento2/releases/tag/3.5.0

For now I am closing this issue. If the issue still persists or if there are any other questions, feel free to place a comment here and we will check if we can reopen the issue if needed.
