### ISSUE TITLE
Not sending email on completed order

### ISSUE THREAD

**Issue by quintenbuis** [MultiSafepay/magento2#8]
When I create an order as a user it doesn't send a confirmation email. Looked through the code but couldn't find a cause. Maybe I'm doing something wrong?

**Comment by vinodsowdagar** [comment]
Hi @quintenbuis ,

The moment the order confirmation e-mail will be sent depends on the following configuration values inside the admin backend. Could you let me know what the values are of the following fields?

Stores > Configuration > Sales > Sales Emails > Order
Stores > Configuration > MultiSafepay > General Settings > Send the order confirmation email

**Comment by quintenbuis** [comment]
**Send the order confirmation email** => after transaction

**Order** => enabled is on

**Comment by quintenbuis** [comment]
Well.. Now it does start sending emails. No idea why it didn't do it earlier.

**Comment by quintenbuis** [comment]
Thought it was fixed but it's still not sending emails. I've put `multisafepay/magento2-msi` in composer replace since it isn't in the project. Maybe something to do with that?

**Comment by vinodsowdagar** [comment]
Hi @quintenbuis ,

It seems that the offline action that should trigger the sending of the e-mail confirmation is not working. This may happen because of various reasons:

- If you are working on a local environment or if you have opened your environment only to certain ip ranges, then the notification controller can not be called by our api, resulting in no offline action being done.

- If MSI is not available anymore in your environment, because of a composer replace, it might also be that the process of creating the invoice and sending the order confirmation e-mail is interrupted due to an error that happens when calling the offline action. In this case i recommend you to look at the following information on our official docs page regarding this matter:
https://docs.multisafepay.com/integrations/ecommerce-integrations/magento2/#4-2-module-dependencies 

If you have any more questions or if you need more help with the installation and configuration of our plugin, please let us know.

**Comment by quintenbuis** [comment]
I am trying to get it to work locally. In the previous repository of multisafepay (multisafepay/magento2msp) it did work locally. Will test it out on a testing environment.

**Comment by quintenbuis** [comment]
I've put it on a testing server but it still isn't sending emails. Also think removing the MSI Module shouldn't impact sending the emails?

**Comment by vinodsowdagar** [comment]
Hi @quintenbuis ,

There might be errors when you remove the MSI module, with MSI still active in your store. If you have removed MSI completely however, it is best to remove the meta-package and instead install the frontend module and the catalog-inventory module only, as stated in our documentation in the link i provided earlier.

If you still see problems after trying to do the above, maybe you can try to call the offline action yourself and check the response. You can find the url of your offline action in the Merchant Control Panel.

Go to Transactions > Transaction Overview > Click on the transaction which you want to call the offline action > Scroll down and on the right of the Offline Actions table you will find an icon and when you click on it you will see the notification_url. You can manually trigger the offline action by going to this URL in your browser. Then you can see what the response is of the offline action. 

I would also recommend to take a look at the following log files to check what is happening:

- php error logs
- var/log/exception.log
- var/log/multisafepay.log

Please let me know if this has helped you. If you need further assistance, please send us an e-mail at integration@multisafepay.com. We can then for example set up a meeting to go over the problem and the steps you have already taken.

**Comment by quintenbuis** [comment]
Hi,

Under `Transactions > Transaction Overview > Click on the transaction` I can't see anything about offline actions. Logs are also clean without any errors.

**Comment by vinodsowdagar** [comment]
Hi @quintenbuis ,

I have one more question. If you set the config `Stores > Configuration > MultiSafepay > General Settings > Send the order confirmation email` to `before transaction`. Do you get a confirmation e-mail when you are being redirected to the payment page?

**Comment by vinodsowdagar** [comment]
Hi @quintenbuis ,

For now i will close this issue due to inactivity.

If you are still encountering this issue, please send us an e-mail at integration@multisafepay.com.
Together with our integration specialists we could take a deeper look into your configuration and investigate further.

**Comment by claudio-ferraro** [comment]
Hi @Vinod-MultiSafepay,

I am experiencing the same problem. No emails are sent from our test environment if the 'after_transaction' or 'after_paid_transaction' settings are used.

Can this issue be reopened?

**Comment by vinodsowdagar** [comment]
Hi @jbclaudio ,

Are your orders going to processing and is an invoice created after completing a transaction? If so, then i will reopen this issue. If not, then please send an e-mail to our integration team at integration@multisafepay.com so they can help you further.
