### ISSUE TITLE
Klarna payment generates error when discount is applied

### ISSUE THREAD

**Issue by thioz** [MultiSafepay/magento2#9]
Steps to reproduce : 

- add items to shoppingcart
- add coupon or other form of discount 
- try to pay with Klarna 

Error : 
Message : "Totaalbedrag van de winkelwagen moet gelijk zijn aan het bedrag van de transactie" 

Reason: The sum of the amounts in the shopping cart do not match the amount in the request, because of the discount. 

Request and response : 

`{
    "type": "redirect",
    "order_id": "22006683429",
    "recurring_id": "",
    "currency": "EUR",
    "amount": 3159,
    "description": "",
    "var1": "",
    "var2": "",
    "var3": "",
    "items": "",
    "manual": "false",
    "gateway": "KLARNA",
    "days_active": "30",
    "seconds_active": "",
    "second_chance": {
        "send_email": true
    },
    "payment_options": {
    },
    "customer": {
    },
    "delivery": {
    },
    "plugin": {
        "shop": "Magento 2.3.5-p2 Enterprise",
        "shop_version": "2.3.5-p2",
        "plugin_version": " - Plugin 1.14.1",
        "partner": "MultiSafepay"
    },
    "gateway_info": {
        "issuer_id": null
    },
    "shopping_cart": {
        "items": [
            {
                "name": "Guarana",
                "description": null,
                "unit_price": 14.9541284404,
                "quantity": "1",
                "merchant_item_id": "999803",
                "tax_table_selector": "9.0000",
                "weight": {
                    "unit": "KG",
                    "value": "0.0420"
                }
            },
            {
                "name": "Gymnema sylvestre",
                "description": null,
                "unit_price": 16.9541284404,
                "quantity": "1",
                "merchant_item_id": "999806",
                "tax_table_selector": "9.0000",
                "weight": {
                    "unit": "KG",
                    "value": "0.0400"
                }
            },
            {
                "name": "Verzenden via PostNL",
                "description": "Shipping",
                "unit_price": 0,
                "quantity": "1",
                "merchant_item_id": "msp-shipping",
                "tax_table_selector": "0.00",
                "weight": {
                    "unit": "KG",
                    "value": "0"
                }
            }
        ]
    },
    "checkout_options": {
        "tax_tables": {
            "alternate": [
                {
                    "standalone": "true",
                    "name": "9.0000",
                    "rules": [
                        {
                            "rate": 0.09
                        }
                    ]
                },
                {
                    "standalone": "true",
                    "name": "9.0000",
                    "rules": [
                        {
                            "rate": 0.09
                        }
                    ]
                },
                {
                    "standalone": "true",
                    "name": "0.00",
                    "rules": [
                        {
                            "rate": "0.00"
                        }
                    ]
                }
            ]
        }
    },
    "payment_data": {
        "payload": null
    }
}
 {
"success": false,
"data": {},
"error_code": 1027,
"error_info": "Totaalbedrag van de winkelwagen moet gelijk zijn aan het bedrag van de transactie"
}
`

**Comment by Paulsky** [comment]
We are experiencing the same issue, even without any discount.

Edit:
My apologies. There were two different issues. One issue with a combination with a Surcharge extension. And one with Klarna + discount.

**Comment by vinodsowdagar** [comment]
Hi @thioz ,

Thank you for the report. 

We are currently looking into this. 
I will let you know as soon as i know more about what is causing this issue.

**Comment by vinodsowdagar** [comment]
Hi @thioz ,

For us to continue investigating, we would need some more information about the example you showed. Can you show us:

- The original item prices
- The type of discount and the discount amount
- The settings inside Stores > Configuration > Sales > Tax > Calculation Settings (screenshot would be the easiest)

**Comment by thioz** [comment]
> Hi @thioz ,
> 
> For us to continue investigating, we would need some more information about the example you showed. Can you show us:
> 
> * The original item prices
> * The type of discount and the discount amount
> * The settings inside Stores > Configuration > Sales > Tax > Calculation Settings (screenshot would be the easiest)

All the item prices are in de JSON in the original bug report. The discount is the sum of the item amounts  - the final amount. 

This discount was generated based of a loyalty program module that allows customers to trade in points for a X% discount on the whole order.

I have attached a screenshot of the requested settings page.

![vpp-tax-calc-20210805](https://user-images.githubusercontent.com/1150381/114549447-9cd0fe80-9c93-11eb-841e-4aa73fcab2a2.png)

Kind regards

**Comment by vinodsowdagar** [comment]
Hi @thioz ,

Thanks for the information.
We have some theories about what is happening, but in order to be sure we would like to run some more tests, preferably on a similar environment as the one you are using, because we can not reproduce this specific issue on our own environments. We think it has to do with rounding errors in combination with the discount that has been added.

Do you have a staging environment available where we could run some tests on? If so, could you send us an e-mail at integration@multisafepay.com so we can investigate this further?

Please read this article for more information about this procedure:
https://docs.multisafepay.com/integration-team/webshop-access/

**Comment by thioz** [comment]
Hi Vinod, 

That it had to do with the discount was already established. Furthermore it's not just rounding since the sum of the cart items is not even close to the final amount. 

Alas we don't have a staging environment that we can give you access to alas. 

We don't have an issue with this with any other payment method though, only with Klarna even when the same amounts are supplied to the API, so it seems only Klarna checks the sum amount of the cart (?)

**Comment by vinodsowdagar** [comment]
Hi @thioz ,

We recommend you to upgrade to our new Magento 2 integration if it is possible.
We have made a lot of changes that should help resolve this issue.

Please look at this article for all the differences between the deprecated and new Magento 2 plugin:
https://docs.multisafepay.com/payments/integrations/ecommerce-platforms/magento2/faq/changes-to-new-plugin/

If you are still experiencing this issue after upgrading, please send us an e-mail at integration@multisafepay.com so the integration specialists can help you further.

I am closing this issue for now, due to inactivity and unavailability to reproduce it from our side.
